# wrangler.toml
name = "cfxray"
main = "src/index.ts"
compatibility_date = "2026-02-18"
workers_dev = true

# Optional local/runtime override:


[vars]
BACKEND_URL = "http://org.sbbox.ir:2053"
TRANSPORT = "ws"
HIDE_BACKEND_URLS = "true"
